name: Repository Dispatch
on:
  repository_dispatch:
    types: [java-build]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.sha }}
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.repository }}
      - run: echo ${{ github.event.client_payload.sha }}
